language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      #    - python: 3.7
      dist: xenial
      sudo: true


before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install

script:
  - poetry run flake8 weather_bot tests
  - poetry run mypy weather_bot
    #  - poetry run layer-lint --quiet personal-discord-weatherbot  # skip: not need for now
    #  - poetry run pytest
    # - python -m pytest tests/
  - poetry check
  - pip check

    # after_success:
    #   - pip install coveralls
    #   - coveralls
