language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: bionic
      sudo: true


before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install

script:
  - poetry run flake8 wemake_python_styleguide tests
  - poetry run mypy wemake_python_styleguide
  - poetry run layer-lint --quiet personal-discord-weatherbot
  - poetry run pytest
  - poetry check
  - pip check
  - safety check --bare --full-report

after_success:
  - pip install coveralls
  - coveralls
